from typing import Protocol

from graft.core.models.rule import RuleEnvelope


class RuleDeployerPort(Protocol):
    def list_rules(self) -> tuple[RuleEnvelope, ...]: ...

    def create_rule(self, rule: RuleEnvelope) -> str: ...

    def update_rule(self, rule: RuleEnvelope) -> None: ...

    def delete_rule(self, rule_id: str) -> None: ...

    def set_rule_state(self, rule_id: str, enabled: bool, alerting: bool) -> None: ...
